### ISSUE TITLE
GeneDataWithRecombination cannot be resolved to a class

### ISSUE THREAD

**Issue by MikeDacre** [dlampart/Pascal#2]
I am trying to compile the project using other branches, and now I am just having two problems, both in GenomeWideScoring.java:

GeneDataWithRecombination and RecombinationRateMap cannot be resolved to types in Eclipse, I can't find the class definitions anywhere. Do you know how I can get around this problem?

I am just trying to find a version of this package that I can run from any location, the main public version can only be run from the root directory of the project.

**Comment by dlampart** [comment]
I added a new fie 'Pascal' to the master branch. replace the 'Pascal' in the package with this file and make it executable. This should allow you to run the package from any directory.  let me know if you still have issues
